sudo: false

language: node_js
node_js:
  - "6"
  - "4"
env:
  - 'TEST_DIR=packages/stylelint-config-itgalaxy'
  - 'TEST_DIR=packages/stylelint-config-itgalaxy-scss'
before_install:
  - 'cd $TEST_DIR'
script:
  - 'npm run travis'
